### PR TITLE
Fix chart update

### LINKED ISSUE #1: chart refresh with long simulation lags entire app
chart should be refreshed with more or less the same performance independently from simulation length

### LINKED ISSUE #2: more varied data to use in rapid simulations
there is a need to prepare a larger file for rapid simulation with varied data so the heatmap that is created afterwards con have values instead of NaN and is helpful in some way

### PR DESCRIPTION
**Pull request by MSSkowron**
Closes #1

### CODE REVIEW

File: gui/src/App.tsx [hunk 1]
```diff
@@ -24,6 +24,23 @@ export const options = {
...
+                text: 'Time (s)',
+            },
+        },
+        y: {
+            title: {
+                display: true,
+                text: 'Number of ill',
+            },
+            min: 0,
+            max: 200,
```
Comment (strjakub) [inline gui/src/App.tsx]: Limit of embedded map is 250, so maybe change it to that? in ideal case it could be parameterized though

**Review by strjakub — COMMENTED** [review]
y axis limit change

**Review by strjakub — APPROVED** [review]

File: gui/src/App.tsx (hunk 1 above)
Comment (MSSkowron) [reply gui/src/App.tsx]: Fixed.
